### PR TITLE
update link to fritzflash.py

### LINKED ISSUE #23: Update releases or edit documentation link
Hi everybody,

the link in the official fritz-tools documentation at
https://fritz-tools.readthedocs.io/de/latest/flashing/windows10.html#download-the-flash-script
points to the releases page of this github repository, which results in the download of an outdated version of the script.

Could you please update the link in the documentation to the latest version
https://raw.githubusercontent.com/freifunk-darmstadt/fritz-tools/master/fritzflash.py
or publish a new release with the latest changes?

Thanks!

### PR DESCRIPTION
**Pull request by maurerle**
fixes #23

### CODE REVIEW

**Comment by herbetom** [comment]
Another option would be to just release a new version.

**Comment by maurerle** [comment]
Yes of course. This would also fix all current users who are getting the old version through the link.
As you are a member, could you please add a new release?

On the other hand, updating the link would solve the problem for future versions without having to release a new version.
This is also in line for the instructions for linux and macos

I would suggest to do both, so that users are always using the latest version, with the additional supported devices.

**Comment by herbetom** [comment]
I've contacted someone with permissions. Currently i'm lacking those for this repo.

**Comment by herbetom** [comment]
Thanks, i've merged this since within the docs for Linux and macOS also the direct URL is used.

**Pull request merged**
